### ISSUE TITLE
ConfigBeanImpl: Avoid casting to SimpleConfig, breaking polymorphism

### ISSUE THREAD

**Issue by InspiredIdealist** [lightbend/config#520]
As it stands today, there is a cast in `ConfigBeanImpl.createInternal()` that assumes the type of passed in `Config` is `SimpleConfig`. There is no reason to cast it, since the method used, `root()`, is part of the `Config` interface. However, I do see that `SimpleConfig` overrides the type associated with `root()`. Perhaps it could be safer to cast that portion instead? Or provide an alternate case to support non-`SimpleConfig` based implementations of `Config`?

[See line #44](https://github.com/lightbend/config/blob/master/config/src/main/java/com/typesafe/config/impl/ConfigBeanImpl.java#L44) to see where the issue is.

This forces my app code to have the workaround `customConfigInstance.root().toConfig()` so that I can use the `ConfigBeanFactory`.

**Comment by havocp** [comment]
As you say, looks like the cast there is because SimpleConfig overrides root() to have a more specific return type (AbstractConfigObject) which in turn has the nonpublic `resolveStatus` method. I'm OK with moving the cast to cast the result of root() instead of casting the config.

Should note here that the docs prominently warn against implementing Config because we can and do add methods to that interface in minor releases. I believe it's also true that some APIs won't work with custom Config subtypes (withFallback perhaps is a notable one), and while this instance of that problem is easy to fix, some of the others (like withFallback) probably are not.

Config is mostly an interface in order to organize code, rather than because it's meant to be subtyped by anyone outside the library, so when implementing it and it breaks something you sort of get both pieces :-)

But if you're fine with that, it's ok to implement the interface if you want, and I'm fine with PRs to fix simple stuff like this.
