### ISSUE TITLE
Loading config from a database

### ISSUE THREAD

**Issue by tgupta1419** [lightbend/config#551]
How do I load a config from a database. Which interface do I need to implement.

**Comment by ktoso** [comment]
There is no such API in this library. It is a minimal config parser library.

You can load a string from wherever and then `ConfigFactory.parseString` it if you want though

**Comment by havocp** [comment]
Rather than implementing an interface the idea would be to build a Config object (for example with parseString as @ktoso mentioned, but could also build one in other ways). Note that while Config is an interface it shouldn’t be implemented by users of the library; use the provided ConfigFactory and ConfigValueFactory to create instances.

Once you have a Config merge it with other Config using withFallback or ConfigFactory.load(Config), the docs and examples show this.

**Comment by tgupta1419** [comment]
@havocp thanks!
